// gsap.to("#box",
//     {
//         x:1000,
//         duration:2,
//         rotate:360,
//         backgroundColor:"red",
//         delay:1
//     }
// )
// gsap.from("#box1",
//     {
//         x:1000,
//         duration:2,
//         rotate:360,
//         backgroundColor:"red",
//         scale:0.6,
//         delay:1
//     }
// )
